version: '3.8'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=projet5
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=projet5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
